# fly.toml app configuration file generated for g6l-go-links on 2024-01-18T12:47:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "g6l-go-links"
primary_region = "bos"

[build]
  dockerfile = "./cmd/go-links/Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
