on:
  push:

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        cache: true
        go-version-file: go.mod
    
    - name: Set up Ko
      uses: ko-build/setup-ko@v0.6
    
    - name: Build container
      run: ko build --bare ./cmd/go-links
    
